### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-paper-ripple#1]
### Roadmap
- [ ] Allow ripple to be triggered by other inputs, like opening of a menu
- [ ] Prop to make ripple fill the size of the window rather than the element
- [ ] Spring config should be based on element size?
